#Generated by Fabric Compiler ( version 2022.2 <build 117120> ) at Fri Oct 27 15:02:03 2023

add_design /anlab/stuhome/zngz17/Lab_work/Float_point/pds_ip_10_27/ipcore/flt_pds2/flt_pds2.idf
add_design "/anlab/stuhome/zngz17/Lab_work/Float_point/pds_ip_10_27/ipcore/flt_pds2/rtl/synplify/div_inv/ipsxe_floating_point_div_inv_v1_0.v"
add_design "/anlab/stuhome/zngz17/Lab_work/Float_point/pds_ip_10_27/ipcore/flt_pds2/rtl/synplify/div_inv/reci_5.v"
add_design "/anlab/stuhome/zngz17/Lab_work/Float_point/pds_ip_10_27/ipcore/flt_pds2/rtl/synplify/div_inv/n_rom.v"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
add_design "/anlab/stuhome/zngz17/Lab_work/Float_point/pds_ip_10_27/APM_ip/GTP_APM_E2.v"
add_design "/anlab/stuhome/zngz17/Lab_work/Float_point/pds_ip_10_27/ipcore/newton_pds/GTP_APM_E2.v"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
enable_pr_flow -syn_tool ads
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
add_constraint "/anlab/stuhome/zngz17/Lab_work/Float_point/pds_ip_10_27/APM_ip/ipsxe_floating_point_core_only.fdc"
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
add_design "/anlab/stuhome/zngz17/Lab_work/Float_point/pds_ip_10_27/APM_ip/GTP_APM_E2.v"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
remove_design -verilog "/anlab/stuhome/zngz17/Lab_work/Float_point/pds_ip_10_27/APM_ip/GTP_APM_E2.v"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
remove_design -verilog "/anlab/stuhome/zngz17/Lab_work/Float_point/pds_ip_10_27/ipcore/newton_pds/GTP_APM_E2.v"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module ipsxe_floating_point_div_inv_v1_0
synthesize -ads -selected_syn_tool_opt 2 
